"""Add User model and relationship to Thought

Revision ID: 25e42abbc7f1
Revises: 2444d9b518ad
Create Date: 2025-04-20 19:16:12.882413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25e42abbc7f1'
down_revision: Union[str, None] = '2444d9b518ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.add_column('thoughts', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_thoughts_user_id'), 'thoughts', ['user_id'], unique=False)
    op.create_foreign_key(op.f('fk_thoughts_user_id_users'), 'thoughts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_thoughts_user_id_users'), 'thoughts', type_='foreignkey')
    op.drop_index(op.f('ix_thoughts_user_id'), table_name='thoughts')
    op.drop_column('thoughts', 'user_id')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
